# Generated by Django 3.0.4 on 2020-03-15 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('platform', models.CharField(max_length=50)),
                ('platform_country', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=50)),
                ('buyer_email', models.CharField(max_length=30)),
                ('buyer_company_name', models.CharField(max_length=30)),
                ('review_quantity', models.IntegerField()),
                ('earning', models.FloatField()),
                ('total_price', models.FloatField()),
                ('days_to_complete', models.IntegerField(default=10)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
