# Generated by Django 3.0.4 on 2020-03-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_auto_20200315_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_country',
            field=models.CharField(default='.com', max_length=10),
        ),
    ]
