# Generated by Django 3.0.4 on 2020-03-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_auto_20200315_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
