# Generated by Django 3.0.4 on 2020-03-15 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_email', models.CharField(max_length=30)),
                ('used_ips', models.CharField(max_length=255)),
                ('bitcoin_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payout_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payout_method', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
    ]
