# Generated by Django 3.0.4 on 2020-03-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20200315_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payout_Request',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
