# Generated by Django 3.0.4 on 2020-03-19 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_task_claimed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Task')),
            ],
        ),
    ]
