# Generated by Django 3.0.4 on 2020-03-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='screenshot',
            field=models.ImageField(default='screenshots/non.jpg', upload_to='screenshots/'),
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
