# Generated by Django 3.0.4 on 2020-03-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_auto_20200320_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='task',
            name='purchased_screenshot',
            field=models.ImageField(default='purchased_screenshots/non.jpg', upload_to='purchased_screenshots/'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_screenshot',
            field=models.ImageField(default='review_screenshots/non.jpg', upload_to='review_screenshots/'),
        ),
    ]
