# Generated by Django 3.0.4 on 2020-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_auto_20200326_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='purchased_screenshot',
        ),
        migrations.AddField(
            model_name='task',
            name='product_screenshot',
            field=models.ImageField(default='product_screenshots/non.jpg', upload_to='product_screenshots/'),
        ),
    ]
