# Generated by Django 3.0.4 on 2020-03-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_auto_20200326_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout_request',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Task'),
        ),
    ]
