# Generated by Django 3.0.4 on 2020-03-26 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_payout_request_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout_request',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout_request',
            name='date_submitted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
