# Generated by Django 3.0.4 on 2020-04-05 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_auto_20200326_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 1, 28, 39, 991768)),
        ),
    ]
