# Generated by Django 3.0.4 on 2020-04-05 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_auto_20200405_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 1, 39, 1, 366254)),
        ),
    ]
