# Generated by Django 3.0.4 on 2020-04-05 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_auto_20200405_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 5, 50, 5, 461231, tzinfo=utc)),
        ),
    ]
