# Generated by Django 2.1 on 2020-04-12 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_auto_20200405_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 6, 58, 5, 873046, tzinfo=utc)),
        ),
    ]
