# Generated by Django 2.1 on 2020-04-19 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_auto_20200412_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='order_notification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 10, 9, 32, 647701, tzinfo=utc)),
        ),
    ]
