# Generated by Django 2.1 on 2020-04-20 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0017_auto_20200419_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 9, 11, 23, 930579, tzinfo=utc)),
        ),
    ]
