# Generated by Django 2.1 on 2020-04-21 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_auto_20200420_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 9, 29, 55, 794011, tzinfo=utc)),
        ),
    ]
