# Generated by Django 2.1 on 2020-04-24 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0019_auto_20200421_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 20, 32, 55, 113574, tzinfo=utc)),
        ),
    ]
