# Generated by Django 2.1 on 2020-04-28 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0021_auto_20200428_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 28, 4, 48, 1, 927064, tzinfo=utc)),
        ),
    ]
