# Generated by Django 2.1 on 2020-04-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0023_auto_20200428_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claimed_date',
            field=models.DateTimeField(),
        ),
    ]
