# Generated by Django 2.1 on 2020-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0024_auto_20200428_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout_request',
            name='amount',
        ),
        migrations.AddField(
            model_name='payout_request',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
