# Generated by Django 2.1 on 2020-05-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0025_auto_20200525_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout_request',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
