# Generated by Django 2.1 on 2020-08-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0027_auto_20200525_2339'),
        ('worker', '0028_auto_20200801_0350'),
    ]

    operations = [
    ]
